services:
  fraud-api:
    build: ./fraud-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./fraud-api/model:/app/model:ro

  stream-service:
    build: ./stream-service
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      FRAUD_API_URL: http://fraud-api:8000
      DATA_FILE_PATH: data/sample_transactions.csv
    volumes:
      - ./stream-service/data:/app/data:ro

  frontend:
    build:
      context: ./frontend
      args:
        VITE_FRAUD_API_URL: ${VITE_FRAUD_API_URL}
        VITE_STREAM_API_URL: ${VITE_STREAM_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - fraud-api
      - stream-service
